[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://cibofdevs.cloud/api"
  REACT_APP_WS_URL = "wss://cibofdevs.cloud"
  REACT_APP_APP_NAME = "EnvPilot"
  REACT_APP_APP_VERSION = "1.0.0"
  REACT_APP_ENABLE_MFA = "true"
  REACT_APP_ENABLE_REAL_TIME_NOTIFICATIONS = "true"
  REACT_APP_ENABLE_ANALYTICS = "true"
  REACT_APP_API_TIMEOUT = "60000"
  REACT_APP_API_RETRY_COUNT = "3"
  REACT_APP_API_RETRY_DELAY = "1000"
  REACT_APP_DEBUG_MODE = "false"
  REACT_APP_LOG_LEVEL = "info"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 